export const NEW_PLOT = 'NEW_PLOT';
export const CHANGE_PROPERTY = 'CHANGE_PROPERTY';
export const CHANGE_RECOUNT = 'CHANGE_RECOUNT';
export const CHANGE_CURENTRECOUNT = 'CHANGE_CURENTRECOUNT';
export const UPDATE_STEPS = 'UPDATE_STEPS';
export const CHANGE_COEFFICIENTS = 'CHANGE_COEFFICIENTS';