export const CHANGE_PROPERTY = 'CHANGE_PROPERTY';
export const CHANGE_RECOUNT = 'CHANGE_RECOUNT';
export const CHANGE_CURENTRECOUNT = 'CHANGE_CURENTRECOUNT';
export const UPDATE_STEPS = 'UPDATE_STEPS';