export const ABRISPRINTFORMS_FILL_SUCCESS = 'ABRISPRINTFORMS_FILL_SUCCESS';
export const ABRISPRINTFORMS_ADD = 'ABRISPRINTFORMS_ADD';
export const ABRISPRINTFORMS_DEL = 'ABRISPRINTFORMS_DEL';
export const ABRISPRINTFORMS_EDIT = 'ABRISPRINTFORMS_EDIT';