export const CUTTINGMETHODS_FILL_SUCCESS = 'CUTTINGMETHODS_FILL_SUCCESS';
export const CUTTINGMETHODS_ADD = 'CUTTINGMETHODS_ADD';
export const CUTTINGMETHODS_DEL = 'CUTTINGMETHODS_DEL';
export const CUTTINGMETHODS_EDIT = 'CUTTINGMETHODS_EDIT';
export const CUTTINGMETHODS_SORT = 'CUTTINGMETHODS_SORT';