export const FEEDRATES_FILL_SUCCESS = 'FEEDRATES_FILL_SUCCESS';
export const FEEDRATES_ADD = 'FEEDRATES_ADD';
export const FEEDRATES_DEL = 'FEEDRATES_DEL';
export const FEEDRATES_EDIT = 'FEEDRATES_EDIT';
export const FEEDRATES_SORT = 'FEEDRATES_SORT';