export const FORESTRY_FILL_SUCCESS = 'FORESTRY_FILL_SUCCESS';
export const FORESTRY_ADD = 'FORESTRY_ADD';
export const FORESTRY_DEL = 'FORESTRY_DEL';
export const FORESTRY_EDIT = 'FORESTRY_EDIT';
export const FORESTRY_SORT = 'FORESTRY_SORT';