export const METHODSCLEANINGS_FILL_SUCCESS = 'METHODSCLEANINGS_FILL_SUCCESS';
export const METHODSCLEANINGS_ADD = 'METHODSCLEANINGS_ADD';
export const METHODSCLEANINGS_DEL = 'METHODSCLEANINGS_DEL';
export const METHODSCLEANINGS_EDIT = 'METHODSCLEANINGS_EDIT';
export const METHODSCLEANINGS_SORT = 'METHODSCLEANINGS_SORT';