export const PRINTFORMS_FILL_SUCCESS = 'PRINTFORMS_FILL_SUCCESS';
export const PRINTFORMS_ADD = 'PRINTFORMS_ADD';
export const PRINTFORMS_DEL = 'PRINTFORMS_DEL';
export const PRINTFORMS_EDIT = 'PRINTFORMS_EDIT';