export const PUBLICATIONS_FILL_SUCCESS = 'PUBLICATIONS_FILL_SUCCESS';
export const PUBLICATIONS_FILL_lISTPUBLICATION = 'PUBLICATIONS_FILL_lISTPUBLICATION';
export const PUBLICATIONS_ADD = 'PUBLICATIONS_ADD';
export const PUBLICATIONS_DEL = 'PUBLICATIONS_DEL';
export const PUBLICATIONS_EDIT = 'PUBLICATIONS_EDIT';
export const PUBLICATIONS_SORT = 'PUBLICATIONS_SORT';