export const SUBFORESTRY_FILL_SUCCESS = 'SUBFORESTRY_FILL_SUCCESS';
export const SUBFORESTRY_ADD = 'SUBFORESTRY_ADD';
export const SUBFORESTRY_DEL = 'SUBFORESTRY_DEL';
export const SUBFORESTRY_EDIT = 'SUBFORESTRY_EDIT';
export const SUBFORESTRY_SORT = 'SUBFORESTRY_SORT';