export const TYPESRATES_FILL_SUCCESS = 'TYPESRATES_FILL_SUCCESS';
export const TYPESRATES_ADD = 'TYPESRATES_ADD';
export const TYPESRATES_DEL = 'TYPESRATES_DEL';
export const TYPESRATES_EDIT = 'TYPESRATES_EDIT';
export const TYPESRATES_SORT = 'TYPESRATES_SORT';
export const TYPESRATES_FILL_REGIONS = 'TYPESRATES_FILL_REGIONS';