export const ABRIS_RESET = 'ABRIS_RESET';
export const ABRIS_RESTORING = 'ABRIS_RESTORING';
export const ABRIS_BACKGROUND_LOAD = 'ABRIS_BACKGROUND_LOAD';
export const ABRIS_BACKGROUND_TARGET = 'ABRIS_BACKGROUND_TARGET';
export const ABRIS_BACKGROUND_CLEAR = 'ABRIS_BACKGROUND_CLEAR';
export const ABRIS_BACKGROUND_SLEEP = 'ABRIS_BACKGROUND_SLEEP';
export const ABRIS_BACKGROUND_LOADIMAGE = 'ABRIS_BACKGROUND_LOADIMAGE';
export const ABRIS_BACKGROUND_SCALE = 'ABRIS_BACKGROUND_SCALE';
export const ABRIS_BACKGROUND_ZOOM = 'ABRIS_BACKGROUND_ZOOM';
export const ABRIS_BACKGROUND_SHIFT = 'ABRIS_BACKGROUND_SHIFT';
export const ABRIS_BACKGROUND_ROTATE = 'ABRIS_BACKGROUND_ROTATE';
export const ABRIS_BACKGROUND_OPACITY = 'ABRIS_BACKGROUND_OPACITY';

export const ABRIS_BACKGROUND_CALIBRATE = 'ABRIS_BACKGROUND_CALIBRATE';
export const ABRIS_BACKGROUND_COEFFICIENTCALIBRATE = 'ABRIS_BACKGROUND_COEFFICIENTCALIBRATE';

export const ABRIS_BACKGROUND_GPS_BINDING = 'ABRIS_BACKGROUND_GPS_BINDING';
export const ABRIS_BACKGROUND_GPS_CALC = 'ABRIS_BACKGROUND_GPS_CALC';

export const ABRIS_BACKGROUND_MAGNETIC_DECLINATION = 'ABRIS_BACKGROUND_MAGNETIC_DECLINATION';


export const ABRIS_RESTORING_OBJECT = 'ABRIS_RESTORING_OBJECT';
export const ABRIS_CTRL_Z_OBJECT = 'ABRIS_CTRL_Z_OBJECT';
export const ABRIS_CREAT_OBJECT = 'ABRIS_CREAT_OBJECT';
export const ABRIS_EDIT_OBJECT = 'ABRIS_EDIT_OBJECT';
export const ABRIS_DELETE_OBJECT = 'ABRIS_DELETE_OBJECT';
export const ABRIS_MODE_OBJECT = 'ABRIS_MODE_OBJECT';
export const ABRIS_CLEAR_CURENT_OBJECT = 'ABRIS_CLEAR_CURENT_OBJECT';
export const ABRIS_CLEAR_OBJECTS = 'ABRIS_CLEAR_OBJECTS';

